project:
  type: default
  output-dir: docs
  render: 
    - index.qmd
    - "!_manuscript/"
    - "!notebooks/01-data-import-clean-process.qmd"
    - "!notebooks/02-crosstables.qmd"
    - "!notebooks/03-plots.qmd"

execute:
  freeze: auto

# bibliography: references.bib
mainfont: Palatino Linotype
date-modified: last-modified
date-format: "YYYY-M-D"

format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: true
    toc-location: left
    title-block-style: default
    title-block-banner: images/CDCE.png
    appendix-style: none
    search: false
    link-citations: true
    css: styles.css
    # notebook-links: global # hold off on this until ready
    fig-responsive: true
    smooth-scroll: true
    embed-resources: true
    link-external-newwindow: true
    footnotes-hover: false
    reference-location: document
    page-layout: article
    lightbox: true
    number-sections: false
    theme:
      light: default
      dark: darkly
    grid: 
      body-width: 900px
    # Use a CSL to style (https://www.zotero.org/styles/)
    # csl: https://www.zotero.org/styles/american-political-science-review
  # docx: default
  # jats: default
  report-pdf:
    keep-md: true
    keep-tex: true
