project:
  type: default
  output-dir: docs
  render: 
    - index.qmd
    - "!_manuscript/"
    - "!notebooks/"

execute:
  freeze: auto

# bibliography: references.bib
mainfont: Palatino Linotype
date-modified: last-modified
date-format: "YYYY-M-D"

format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: true
    toc-location: left
    title-block-style: manuscript
    appendix-style: none
    theme:
      light: default
      dark: default
    smooth-scroll: true
    embed-resources: true
    link-external-newwindow: true
    footnotes-hover: false
    reference-location: margin
    page-layout: article
    grid: 
      body-width: 900px
    code-tools: true
    code-fold: true
    # Use a CSL to style (https://www.zotero.org/styles/)
    # csl: https://www.zotero.org/styles/american-political-science-review
  # docx: default
  # jats: default
  # report-pdf:
  #   keep-md: true
  #   keep-tex: true
