project:
  type: default
  output-dir: docs
  render: 
    - index.qmd
    - "!_manuscript/"
    - "!notebooks/"

execute:
  freeze: auto

# bibliography: references.bib
mainfont: Palatino Linotype
date-modified: last-modified
date-format: "YYYY-M-D"

format:
  html:
    toc: true
    toc-location: left
    title-block-style: manuscript
    smooth-scroll: true
    embed-resources: true
    link-external-newwindow: true
    footnotes-hover: false
    page-layout: article
    code-tools: true
    code-fold: true
    code-overflow: wrap
    code-copy: hover
    code-links:
      - text: Data Import and Processing
        icon: file-code
        href: 01-data-import-clean-process.qmd
      - repo
    # Use a CSL to style (https://www.zotero.org/styles/)
    # csl: https://www.zotero.org/styles/american-political-science-review
  # docx: default
  # jats: default
  report-pdf:
    keep-md: true
    keep-tex: true
