---
title: "Survey Experiment"
author:
  - name: Isaiah
    #orcid: 0000-0002-0760-5497
    #corresponding: true
    degrees:
    email: gespinoz@umd.edu
    roles:
      - Research Assistant
      - Reviewer
      - Analyst
    affiliations:
      - Center for Democracy and Civic Engagement
      - University of Maryland at College Park 
  # - name: Rowan Cockett
  #   orcid: 0000-0002-7859-8394
  #   corresponding: false
  #   roles: []
  #   affiliations:
  #     - Curvenote

phone: (410) 903 6911
email: ssnovey@umd.edu
department: Center for Democracy and Civic Engagement
keywords:
  - Election Workers
  - Poll workers
  - Veterans
  - Public opinion
  - Election administration
plain-language-summary: |
  Analysis and results of survey experiment.
key-points:  
  - Lorem ipsum odor amet, consectetuer adipiscing elit.
  - Lorem ipsum odor amet, consectetuer adipiscing elit.
  - Lorem ipsum odor amet, consectetuer adipiscing elit.
date: 2024-09-12
# bibliography: references.bib
# csl: american-political-science-association.csl
link-citations: true
code-tools: 
    source: https://github.com/isaiahespi/cdce_vets/blob/4953d971910f5040e0fe591e65e807adf5a198f5/index.qmd
fig-responsive: true
smooth-scroll: true
embed-resources: true
link-external-newwindow: true
footnotes-hover: false
reference-location: document
page-layout: article
lightbox: true
citation:
  container-title: Center for Democracy and Civic Engagement, University of Maryland
number-sections: false
execute: 
  cache: false
  echo: false 
---


::: {.cell}

:::

::: {.cell}

:::




## Key Questions

The following presents some key results from the survey experiment.

### Q19




::: {.cell .tbl-column-margin .fig-cap-location-top tbl-cap='Confidence vote counts will be accurate in Maricopa County, AZ by Experiment Condition'}
::: {.cell-output-display}
\begingroup
\setlength{\LTpost}{0mm}
\begin{longtable}{lllll}
\toprule
 & \multicolumn{4}{c}{{\bfseries Q19. Vote Count Confidence for Maricopa County, AZ}\textsuperscript{\textit{1}}} \\ 
\cmidrule(lr){2-5}
Group & {\bfseries Not at all confident} & {\bfseries Not too confident} & {\bfseries Somewhat confident} & {\bfseries Very confident} \\ 
\midrule\addlinespace[2.5pt]
Control & 3.8 (24) & 17.1 (107) & 49.2 (307) & 29.8 (186) \\ 
Treatment & 3.9 (25) & 12.7  (81) & 46.6 (298) & 36.8 (235) \\ 
\bottomrule
\end{longtable}
\begin{minipage}{\linewidth}
Table reflects row percentages. NAs omitted\\
\textsuperscript{\textit{1}}Q19. How confident are you that votes in Maricopa County, AZ will be counted as voters intend in the elections this November?\\
\end{minipage}
\endgroup


Confidence in Accurate Vote Count by Experiment Condition
:::

::: {.cell-output-display}
![Confidence in Accurate Vote Count by Experiment Condition](index_files/figure-pdf/unnamed-chunk-3-1.pdf)
:::
:::





### Q22 




::: {.cell .tbl-column-margin .fig-cap-location-top tbl-cap='Q22. Confidence in Fair Voting Process by Experiment Condition in Maricopa County, AZ by Experiment Condition'}
::: {.cell-output-display}
\begingroup
\setlength{\LTpost}{0mm}
\begin{longtable}{lllll}
\toprule
 & \multicolumn{4}{c}{{\bfseries Q22. Confidence in Fair Voting Process for Maricopa County, AZ}\textsuperscript{\textit{1}}} \\ 
\cmidrule(lr){2-5}
Group & {\bfseries Not at all confident} & {\bfseries Not too confident} & {\bfseries Somewhat confident} & {\bfseries Very confident} \\ 
\midrule\addlinespace[2.5pt]
Control & 4.8 (30) & 18.9 (118) & 45.2 (282) & 31.1 (194) \\ 
Treatment & 4.2 (27) & 12.2  (78) & 46.3 (296) & 37.2 (238) \\ 
\bottomrule
\end{longtable}
\begin{minipage}{\linewidth}
Table reflects row percentages. NAs omitted\\
\textsuperscript{\textit{1}}Q22.How confident are you that the voting process will be fair in Maricopa County, AZ?\\
\end{minipage}
\endgroup


Confidence in Fair Voting Process by Experiment Condition
:::

::: {.cell-output-display}
![Confidence in Fair Voting Process by Experiment Condition](index_files/figure-pdf/unnamed-chunk-4-1.pdf)
:::
:::





### Q25




::: {.cell .tbl-column-margin .fig-cap-location-top tbl-cap='Concern for violence, threats, or voter intimidation in Maricopa County, AZ by Experiment Condition'}
::: {.cell-output-display}
\begingroup
\setlength{\LTpost}{0mm}
\begin{longtable}{lllll}
\toprule
 & \multicolumn{4}{c}{{\bfseries Concern for violence, threats, or voter intimidation in Maricopa County, AZ}\textsuperscript{\textit{1}}} \\ 
\cmidrule(lr){2-5}
Group & {\bfseries Not at all concerned} & {\bfseries Not too concerned} & {\bfseries Somewhat concerned} & {\bfseries Very concerned} \\ 
\midrule\addlinespace[2.5pt]
Control & 12.8  (80) & 34.0 (212) & 41.0 (256) & 12.2 (76) \\ 
Treatment & 16.1 (103) & 38.5 (246) & 34.1 (218) & 11.3 (72) \\ 
\bottomrule
\end{longtable}
\begin{minipage}{\linewidth}
Table reflects row percentages. NAs omitted\\
\textsuperscript{\textit{1}}Q25. Thinking about Maricopa County, AZ, how concerned should voters feel 
about potential violence, 
threats of violence, or intimidation while voting in person at their local polling place?\\
\end{minipage}
\endgroup


Concern for violence, threats, or voter intimidation in Maricopa County, AZ by Experiment Condition
:::

::: {.cell-output-display}
![Concern for violence, threats, or voter intimidation in Maricopa County, AZ by Experiment Condition](index_files/figure-pdf/unnamed-chunk-5-1.pdf)
:::
:::




### Q26




::: {.cell .tbl-column-margin .fig-cap-location-top tbl-cap='Q26. In-person voter safety in Maricopa County, AZ by Experiment Condition'}
::: {.cell-output-display}
![In-person voter safety in Maricopa County, AZ by Experiment Condition](index_files/figure-pdf/unnamed-chunk-6-1.pdf)
:::

::: {.cell-output-display}
\begingroup
\setlength{\LTpost}{0mm}
\begin{longtable}{lllll}
\toprule
 & \multicolumn{4}{c}{{\bfseries Confidence for In-person voter safety in Maricopa County, AZ}\textsuperscript{\textit{1}}} \\ 
\cmidrule(lr){2-5}
Group & {\bfseries Not at all confident} & {\bfseries Not too confident} & {\bfseries Somewhat confident} & {\bfseries Very confident} \\ 
\midrule\addlinespace[2.5pt]
Control & 4.5 (28) & 17.5 (109) & 53.8 (336) & 24.2 (151) \\ 
Treatment & 3.8 (24) & 11.6  (74) & 52.2 (333) & 32.4 (207) \\ 
\bottomrule
\end{longtable}
\begin{minipage}{\linewidth}
Table reflects row percentages. NAs omitted\\
\textsuperscript{\textit{1}}Q26. How confident, if at all, are you that in person polling places in Maricopa County, AZ 
will be safe places for voters to cast their ballots during the upcoming elections in November?\\
\end{minipage}
\endgroup


In-person voter safety in Maricopa County, AZ by Experiment Condition
:::
:::

::: {.cell .fig-cap-location-top}
::: {.cell-output-display}
![Confidence in Election Administration by Experiment Condition](index_files/figure-pdf/unnamed-chunk-7-1.pdf)
:::
:::


{{< pagebreak >}}









## Survey Questions by Treatment Condition

### Trust and Confidence in AZ Elections


The following cross-tables break down relative observations and percentages of responses to survey questions across categories of the survey's experimental condition. The survey questions in the table below concerned a respondent's degree of trust and confidence in the electoral process in Maricopa County, AZ.




::: {#tbl-1 .cell .column-page tbl-cap='Trust and Confidence in Maricopa County, AZ Elections by Treatment Condition'}
\begin{table}
\centering\begingroup\fontsize{13}{15}\selectfont

\begin{tabular}[t]{llll}
\toprule
  & Control & Treatment & P-value\\
\midrule
 & (N=624) & (N=639) & \\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Confidence vote counts will be accurate, AZ}}\\
\hspace{1em}Not\_confident & 131 (21.0\%) & 106 (16.6\%) & 0.0533\\
\hspace{1em}Confident & 493 (79.0\%) & 533 (83.4\%) & \\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Competence of Election Staff, AZ}}\\
\hspace{1em}Not\_confident & 129 (20.7\%) & 103 (16.1\%) & 0.0451\\
\hspace{1em}Confident & 495 (79.3\%) & 535 (83.7\%) & \\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Commitment of Election Staff, AZ}}\\
\hspace{1em}not\_committed & 106 (17.0\%) & 94 (14.7\%) & 0.303\\
\hspace{1em}committed & 518 (83.0\%) & 545 (85.3\%) & \\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Fair Process, AZ}}\\
\hspace{1em}Not\_confident & 148 (23.7\%) & 105 (16.4\%) & 0.00155\\
\hspace{1em}Confident & 476 (76.3\%) & 534 (83.6\%) & \\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Fair Outcomes, AZ}}\\
\hspace{1em}Not\_confident & 139 (22.3\%) & 116 (18.2\%) & 0.0817\\
\hspace{1em}Confident & 485 (77.7\%) & 522 (81.7\%) & \\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Security of Voting Tech, AZ}}\\
\hspace{1em}Not\_confident & 188 (30.1\%) & 147 (23.0\%) & 0.00479\\
\hspace{1em}Confident & 435 (69.7\%) & 492 (77.0\%) & \\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Voters Will Be Free From Intimidation/Violence, AZ}}\\
\hspace{1em}not\_concerned & 292 (46.8\%) & 349 (54.6\%) & 0.00646\\
\hspace{1em}concerned & 332 (53.2\%) & 290 (45.4\%) & \\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Safe In-person Voting, AZ}}\\
\hspace{1em}Not\_confident & 137 (22.0\%) & 98 (15.3\%) & 0.00332\\
\hspace{1em}Confident & 487 (78.0\%) & 540 (84.5\%) & \\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Election Official Approval, AZ}}\\
\hspace{1em}disapprove & 160 (25.6\%) & 134 (21.0\%) & 0.0618\\
\hspace{1em}approve & 463 (74.2\%) & 502 (78.6\%) & \\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Adopt AZ Program}}\\
\hspace{1em}oppose & 170 (27.2\%) & 144 (22.5\%) & 0.059\\
\hspace{1em}support & 452 (72.4\%) & 494 (77.3\%) & \\
\bottomrule
\multicolumn{4}{l}{\rule{0pt}{1em}\textit{Note: }}\\
\multicolumn{4}{l}{\rule{0pt}{1em}makecell[l]{Table reflects column percentages. \P-values based on Pearson's Chi-squared test of independence.}}\\
\end{tabular}
\endgroup{}
\end{table}
:::




### Expectation of Electoral Fraud

The next figure and table reviews a set of questions designed to assess a respondent's expectation of electoral fraud of some sort in Maricopa County, AZ. Again, responses are compared across categories of the survey experiment.

For each of the following five statements, survey participants responded with their expectations of the likelihood that each would occur in Maricopa County, Arizona this election cycle on a scale of "Not likely at all" to "Very likely". The five statements were prefaced with the question, "How likely do you think any or all of the following will happen during this year´s elections in Maricopa County, AZ?"

1.    There will be voter fraud, that is, people who are not eligible to vote will vote, or vote more than once;
2.    Many votes will not actually be counted
3.    Many people will show up to vote and be told they are not eligible
4.    A foreign country will tamper with the votes cast in this area to change the results
5.    Election officials in Maricopa County, Arizona will try to discourage some people from voting




::: {.cell}
::: {.cell-output-display}
![Expectation of Electoral Fraud in Maricopa County, AZ by Experiment Condition](index_files/figure-pdf/fig-q28-1.pdf){#fig-q28}
:::
:::

::: {#tbl-2 .cell .column-page tbl-cap='Expectation of Electoral Fraud in Maricopa County, AZ by Treatment Condition'}
<table style="NAborder-bottom: 0; font-size: 13px; margin-left: auto; margin-right: auto;" class="table table-striped table-bordered table-condensed table-responsive">
 <thead>
  <tr>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">   </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> Control </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> Treatment </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> P-value </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> (N=624) </td>
   <td style="text-align:left;"> (N=639) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr grouplength="2"><td colspan="4" style="border-bottom: 1px solid;"><strong>Voter fraud, AZ</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Not_likely </td>
   <td style="text-align:left;"> 337 (54.0%) </td>
   <td style="text-align:left;"> 374 (58.5%) </td>
   <td style="text-align:left;"> 0.126 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Likely </td>
   <td style="text-align:left;"> 286 (45.8%) </td>
   <td style="text-align:left;"> 265 (41.5%) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr grouplength="2"><td colspan="4" style="border-bottom: 1px solid;"><strong>Votes won't be counted, AZ</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Not_likely </td>
   <td style="text-align:left;"> 355 (56.9%) </td>
   <td style="text-align:left;"> 405 (63.4%) </td>
   <td style="text-align:left;"> 0.0215 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Likely </td>
   <td style="text-align:left;"> 268 (42.9%) </td>
   <td style="text-align:left;"> 233 (36.5%) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr grouplength="2"><td colspan="4" style="border-bottom: 1px solid;"><strong>People will turned away, AZ</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Not_likely </td>
   <td style="text-align:left;"> 317 (50.8%) </td>
   <td style="text-align:left;"> 370 (57.9%) </td>
   <td style="text-align:left;"> 0.0132 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Likely </td>
   <td style="text-align:left;"> 306 (49.0%) </td>
   <td style="text-align:left;"> 268 (41.9%) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr grouplength="2"><td colspan="4" style="border-bottom: 1px solid;"><strong>Foreign interference with votes, AZ</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Not_likely </td>
   <td style="text-align:left;"> 411 (65.9%) </td>
   <td style="text-align:left;"> 434 (67.9%) </td>
   <td style="text-align:left;"> 0.499 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Likely </td>
   <td style="text-align:left;"> 212 (34.0%) </td>
   <td style="text-align:left;"> 205 (32.1%) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr grouplength="2"><td colspan="4" style="border-bottom: 1px solid;"><strong>EOs discourage people from voting, AZ</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Not_likely </td>
   <td style="text-align:left;"> 376 (60.3%) </td>
   <td style="text-align:left;"> 439 (68.7%) </td>
   <td style="text-align:left;"> 0.00236 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Likely </td>
   <td style="text-align:left;"> 247 (39.6%) </td>
   <td style="text-align:left;"> 200 (31.3%) </td>
   <td style="text-align:left;">  </td>
  </tr>
</tbody>
<tfoot>
<tr><td style="padding: 0; " colspan="100%"><span style="font-style: italic;">Note: </span></td></tr>
<tr><td style="padding: 0; " colspan="100%">
<sup></sup> Table reflects column percentages. <br>P-values based on Pearson's Chi-squared test of independence.</td></tr>
</tfoot>
</table>
:::




# 3-way Crosstables 

::: {.callout-note}
This section is under construction. A select number of 3-way cross tables will be presented here.
:::





::: {#tbl-q19q7 .cell tbl-cap='Confidence in Accurate Vote Counts among those who do and do not believe the 2020 election was legitimate by Treatment Condition'}
::: {.cell-output-display}
\begingroup
\setlength{\LTpost}{0mm}
\begin{longtable}{lllll}
\toprule
 & \multicolumn{4}{c}{{\bfseries Q19. Vote Count Confidence for Maricopa County, AZ}\textsuperscript{\textit{1}}} \\ 
\cmidrule(lr){2-5}
Q7. Legitimacy of 2020 Election\textsuperscript{\textit{2}} & {\bfseries Not at all confident} & {\bfseries Not too confident} & {\bfseries Somewhat confident} & {\bfseries Very confident} \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{l}{{\bfseries Control}} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Legitimate & 1.18  (5) & 10.85 (46) & 48.35 (205) & 39.62 (168) \\ 
Not legitimate & 9.50 (19) & 30.50 (61) & 51.00 (102) & 9.00  (18) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{l}{{\bfseries Treatment}} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Legitimate & 2.58 (11) & 9.39 (40) & 42.25 (180) & 45.77 (195) \\ 
Not legitimate & 6.25 (13) & 19.23 (40) & 55.77 (116) & 18.75  (39) \\ 
\bottomrule
\end{longtable}
\begin{minipage}{\linewidth}
Table reflects row percentages. NAs omitted\\
\textsuperscript{\textit{1}}Q19. How confident are you that votes in Maricopa County, AZ will be counted as voters intend in the elections this November?\\
\textsuperscript{\textit{2}}Q7.Regardless of whom you supported in the 2020 election, 
do you think Joe Biden's election as president was legitimate, or was he not legitimately elected?\\
\end{minipage}
\endgroup

:::
:::









## Impacts on Confidence

### Impact on confidence in fairness and accuracy of elections

The following examines survey questions that asked respondents whether particular circumstances or election official actions would have any impact on their confidence in the fairness and accuracy of elections. Survey participants responded to six statements, all prefaced with the following,

> "Regardless of whether any of these are actually the case, how would the following impact your confidence in the fairness and accuracy of elections conducted this November?"

1.    Election officials test every machine used in the election to ensure they are secure.
2.    Election officials conduct audits of ballots after every election to confirm the results were accurate.
3.    Poll watchers affiliated with the political parties or candidates observe the election.
4.    Election staff and volunteers include military veterans and their family members from the community[^1].
5.    Election staff and volunteers include lawyers from the community.
6.    Election staff and volunteers include college students from the community.

For each statement, survey participants responded by selecting one of five response options:

1.    Decrease confidence a lot
2.    Decrease confidence somewhat
3.    No impact on confidence
4.    Increase confidence somewhat
5.    Increase confidence a lot


The primary interest concerned whether confidence in election fairness would increase or decreased based on the composition of election staff and volunteers. Of particular importance are responses to the statement which asked respondents to consider whether inclusion of military veterans and veteran's family members as election staff and volunteers has any impact on their confidence in the fairness and accuracy of elections in November. In this case, significant differences were observed between treatment and control groups. 

The figure below displays a clear boost in confidence when election staff includes veterans and family members, but most especially for those who were in the treatment group. That is, the percentage of people who said their confidence in election fairness would increase when election staff includes veterans was about 11.6 percentage points higher than those who said the same in the control group.

::: {.panel-tabset}

## Fig Q41




::: {.cell .fig-column-page-inset-right}
::: {.cell-output-display}
![](index_files/figure-pdf/fig-q41-1.pdf){#fig-q41}
:::
:::






## Q41 Coef Plot




::: {.cell .fig-column-page-inset-right}
::: {.cell-output-display}
![](index_files/figure-pdf/fig-q41-coef-plot-1.pdf){#fig-q41-coef-plot}
:::
:::




:::

An 11.6 percentage point difference was observed between treatment and control groups among those who reported that their confidence in the fairness and accuracy of elections would "increase a lot" or "increase somewhat" when election staff and volunteers include (or consist of a majority of) military service veterans and their family members in the community. This difference was estimated with 95% confidence to be statistically significant (p < 0.01, CI [-0.169, -0.057]).  Conversely, no difference was observed between treatment and control groups among those who reported that their confidence would "decrease a lot" or "decrease somewhat".


[^1]: Two different versions of this statement was presented to survey participants. Half of the sample read the statement as, "Election staff and volunteers *include* military veterans and their family members from the community", whereas the other half of the sample read, "The *majority* of election staff and volunteers consist of military veterans and their family members from the community." No significant differences in responses were observed between those who read one version of the statement over the other. However, the same was done for statements number 5 and 6 which concern "lawyers from the community" and "college students from the community". Significant differences were found when comparing responses between the different versions of these statements. See the appendix for further discussion on these results.  


In the following table, responses were collapsed into three categories. Any increase in confidence (e.g., increase confidence a lot, increase confidence somewhat) were collapsed into one column, and likewise for any response indicating a decrease in confidence.




::: {#tbl-4 .cell .column-body-outset-right tbl-cap='Confidence Impact on Election Fairness and Accuracy'}
\begingroup\fontsize{13}{15}\selectfont

\begin{tabu} to \linewidth {>{\raggedright}X>{\raggedright}X>{\raggedright}X>{\raggedright}X>{\raggedright}X}
\hline
Condition/Election staff include veterans and family & Decrease Confidence & No Impact & Increase Confidence & Total\\
\hline
Control & 10.11\%  (63) & 44.78\% (279) & 45.10\% (281) & 100.00\%   (623)\\
\hline
Treatment & 8.62\%  (55) & 34.64\% (221) & 56.74\% (362) & 100.00\%   (638)\\
\hline
Total & 9.36\% (118) & 39.65\% (500) & 50.99\% (643) & 100.00\% (1,261)\\
\hline
\multicolumn{5}{l}{\rule{0pt}{1em}\textit{Note: }}\\
\multicolumn{5}{l}{\rule{0pt}{1em}NA omitted. \% (n)}\\
\end{tabu}
\endgroup{}
:::







These results suggest that reading a vignette about county efforts to recruit veterans as election staff and volunteers does more to increase one's confidence in the fairness and accuracy of elections, especially under the prospect that election staff and volunteers would include veterans and their family members.

### Impact on Confidence in Voter Safety at polling sites


The same analysis was conducted for questions that assessed the reported impact on confidence that voters would be safe to vote in-person. Survey participants provided responses to the same six statements as before, which were all prefaced with the following question,

> "How would the following impact your confidence that voters are safe from violence, threats of violence, or intimidation while voting in-person during elections this November?"

Again, the bar graph below displays a clear boost among participants in the treatment group who reported that their confidence in voter safety would increase when election staff is said to include veterans and their family members. 

::: {.panel-tabset}

## Fig Q43




::: {.cell .fig-column-page-inset-right}
::: {.cell-output-display}
![](index_files/figure-pdf/fig-q43-1.pdf){#fig-q43}
:::
:::






## Q43 Coef Plot




::: {.cell .fig-column-page-inset-right}
::: {.cell-output-display}
![](index_files/figure-pdf/fig-q43-coefplot-1.pdf){#fig-q43-coefplot}
:::
:::




:::

The proportion of people who said their confidence in voter safety would increase when election staff includes veterans was about 8.4 percentage points higher than those who said the same in the control group.





::: {#tbl-7 .cell tbl-cap='Confidence Impact on In-person Voter Safety'}
\begingroup\fontsize{13}{15}\selectfont

\begin{tabu} to \linewidth {>{\raggedright}X>{\raggedright}X>{\raggedright}X>{\raggedright}X>{\raggedright}X}
\hline
Condition/Election staff include veterans and family & Decrease Confidence & No Impact & Increase Confidence & Total\\
\hline
Control & 12.20\%  (76) & 38.68\% (241) & 49.12\% (306) & 100.00\%   (623)\\
\hline
Treatment & 9.09\%  (58) & 33.39\% (213) & 57.52\% (367) & 100.00\%   (638)\\
\hline
Total & 10.63\% (134) & 36.00\% (454) & 53.37\% (673) & 100.00\% (1,261)\\
\hline
\multicolumn{5}{l}{\rule{0pt}{1em}\textit{Note: }}\\
\multicolumn{5}{l}{\rule{0pt}{1em}NA omitted. \% (n)}\\
\end{tabu}
\endgroup{}
:::





# Sample Demographics and Balance

The decision was made to exclude any respondents who didn't complete the survey. There were a total of 125 respondents who started but didn't finish the survey. Of those 125, 105 quit before reaching `Q40_1`, whereas the rest exited the survey after that question[^2].

[^2]: Due to the programming of the survey, respondents were randomly assigned to either question set 'A' or question set 'B'. The grouping variable in the data set is `Qset`. Those respondents assigned to `Qset A` answered questions `Q41` and `Q43`; those assigned to `Qset B` answered question `Q44` and `Q46`. For each question, respondents were presented six statements and selected a response on a 5-point scale from "Decrease Confidence a lot" to "Increase confidence a lot". The six statements were the same for each question. This resulted in six variables per question within the data set (e.g., Q41_1 to Q41_6), where each variable consisted of responses to one of the six particular statements. Tests of differences in proportion between the question sets determined that responses were mostly equivalent between question sets (i.e., no statistically significant differences between proportions) except for the fifth and sixth statements pertaining to lawyers and college students. More detailed information on the results of this analysis are given in a supplementary document. 

 `NA` missing values from the `Qset` variable removes those 105 partial survey responses, i.e., respondents who quit prior to reaching `Q40`.





::: {#tbl-demog .cell .column-page tbl-cap='Survey sample characteristics by treatment condition'}
\begingroup\fontsize{13}{15}\selectfont

\begin{tabu} to \linewidth {>{\raggedright}X>{\raggedright}X>{\raggedright}X>{\raggedright}X}
\toprule
  & Control & Treatment & Overall\\
\midrule
 & (N=624) & (N=639) & (N=1263)\\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Age categorized into eight groups}}\\
\hspace{1em}18-24 & 56 (9.0\%) & 51 (8.0\%) & 107 (8.5\%)\\
\hspace{1em}25-34 & 107 (17.1\%) & 127 (19.9\%) & 234 (18.5\%)\\
\hspace{1em}35-44 & 130 (20.8\%) & 121 (18.9\%) & 251 (19.9\%)\\
\hspace{1em}45-54 & 113 (18.1\%) & 110 (17.2\%) & 223 (17.7\%)\\
\hspace{1em}55-64 & 124 (19.9\%) & 115 (18.0\%) & 239 (18.9\%)\\
\hspace{1em}65-74 & 70 (11.2\%) & 74 (11.6\%) & 144 (11.4\%)\\
\hspace{1em}75-84 & 20 (3.2\%) & 36 (5.6\%) & 56 (4.4\%)\\
\hspace{1em}85-92 & 4 (0.6\%) & 5 (0.8\%) & 9 (0.7\%)\\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{What is your current gender?}}\\
\hspace{1em}Male & 285 (45.7\%) & 307 (48.0\%) & 592 (46.9\%)\\
\hspace{1em}Female & 329 (52.7\%) & 326 (51.0\%) & 655 (51.9\%)\\
\hspace{1em}Other/Refused & 10 (1.6\%) & 6 (0.9\%) & 16 (1.3\%)\\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Primary race reported by respondent}}\\
\hspace{1em}White or Caucasian & 476 (76.3\%) & 493 (77.2\%) & 969 (76.7\%)\\
\hspace{1em}Black or African American & 82 (13.1\%) & 79 (12.4\%) & 161 (12.7\%)\\
\hspace{1em}American Indian & 10 (1.6\%) & 12 (1.9\%) & 22 (1.7\%)\\
\hspace{1em}Asian & 26 (4.2\%) & 30 (4.7\%) & 56 (4.4\%)\\
\hspace{1em}Other & 30 (4.8\%) & 25 (3.9\%) & 55 (4.4\%)\\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Highest level of education completed}}\\
\hspace{1em}Less than high school degree & 20 (3.2\%) & 14 (2.2\%) & 34 (2.7\%)\\
\hspace{1em}High school graduate (high school diploma or equivalent including GED) & 152 (24.4\%) & 174 (27.2\%) & 326 (25.8\%)\\
\hspace{1em}Some college but no degree & 141 (22.6\%) & 140 (21.9\%) & 281 (22.2\%)\\
\hspace{1em}Associate degree in college (2-year) & 69 (11.1\%) & 68 (10.6\%) & 137 (10.8\%)\\
\hspace{1em}Bachelor's degree in college (4-year) & 166 (26.6\%) & 156 (24.4\%) & 322 (25.5\%)\\
\hspace{1em}Master's degree & 61 (9.8\%) & 69 (10.8\%) & 130 (10.3\%)\\
\hspace{1em}Doctoral degree & 5 (0.8\%) & 13 (2.0\%) & 18 (1.4\%)\\
\hspace{1em}Professional degree (JD, MD) & 10 (1.6\%) & 5 (0.8\%) & 15 (1.2\%)\\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Party ID 3 categories, with true Independents}}\\
\hspace{1em}Republican & 261 (41.8\%) & 276 (43.2\%) & 537 (42.5\%)\\
\hspace{1em}Democrat & 282 (45.2\%) & 283 (44.3\%) & 565 (44.7\%)\\
\hspace{1em}Independent & 81 (13.0\%) & 79 (12.4\%) & 160 (12.7\%)\\
\hspace{1em}Missing & 0 (0\%) & 1 (0.2\%) & 1 (0.1\%)\\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Have you ever served in the Armed Forces?}}\\
\hspace{1em}Yes & 53 (8.5\%) & 68 (10.6\%) & 121 (9.6\%)\\
\hspace{1em}No & 571 (91.5\%) & 571 (89.4\%) & 1142 (90.4\%)\\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Are you now serving in the Armed Forces?}}\\
\hspace{1em}Yes & 5 (0.8\%) & 10 (1.6\%) & 15 (1.2\%)\\
\hspace{1em}No & 48 (7.7\%) & 58 (9.1\%) & 106 (8.4\%)\\
\hspace{1em}Missing & 571 (91.5\%) & 571 (89.4\%) & 1142 (90.4\%)\\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Member of immediate family served or is currently serving}}\\
\hspace{1em}Yes & 215 (34.5\%) & 223 (34.9\%) & 438 (34.7\%)\\
\hspace{1em}No & 409 (65.5\%) & 416 (65.1\%) & 825 (65.3\%)\\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Q66. Turnout 2020}}\\
\hspace{1em}Didn't vote & 129 (20.7\%) & 117 (18.3\%) & 246 (19.5\%)\\
\hspace{1em}Unsure/Ineligible & 49 (7.9\%) & 52 (8.1\%) & 101 (8.0\%)\\
\hspace{1em}Voted & 446 (71.5\%) & 470 (73.6\%) & 916 (72.5\%)\\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Who did you vote for?}}\\
\hspace{1em}Donald Trump & 214 (34.3\%) & 222 (34.7\%) & 436 (34.5\%)\\
\hspace{1em}Joe Biden & 252 (40.4\%) & 272 (42.6\%) & 524 (41.5\%)\\
\hspace{1em}Other & 30 (4.8\%) & 28 (4.4\%) & 58 (4.6\%)\\
\hspace{1em}Missing & 128 (20.5\%) & 117 (18.3\%) & 245 (19.4\%)\\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Do you plan to vote?}}\\
\hspace{1em}Yes & 500 (80.1\%) & 532 (83.3\%) & 1032 (81.7\%)\\
\hspace{1em}No & 56 (9.0\%) & 54 (8.5\%) & 110 (8.7\%)\\
\hspace{1em}Undecided & 68 (10.9\%) & 53 (8.3\%) & 121 (9.6\%)\\
\bottomrule
\multicolumn{4}{l}{\rule{0pt}{1em}Table reflects column percentages.}\\
\end{tabu}
\endgroup{}
:::





# Appendix {.appendix}


