---
title: Collapse Factors and Create Dummy Variables
author: Isaiah
---

# Dummy my factors

Collapse categorical variables into Dummy variables

```{r}


# collapse factor vars and add new collapsed factors to data frame
dumdf <- data |>
  select(rowID, q19, q20, q22, q23, q24, q26, q30, q31, q33, q34, q35, q37) |>
  mutate(across(
    c(q19, q20, q22, q23, q24, q26, q30, q31, q33, q34, q35, q37),
    ~ forcats::fct_collapse(
      .,
      Not_confident = c("Not at all confident", "Not too confident"),
      Confident = c("Somewhat confident", "Very confident")
    ),
    .names = "{.col}_2lvl"
  ))

dumdf <- dumdf |> 
  select(rowID, contains("_2lvl")) |> 
  pewmethods::dummify_factors(sep = "_")

dumdf <- dumdf |>
  select(rowID, contains("_2lvl")) |>
  mutate(
    q19_dum = dplyr::case_when(
      q19_2lvl_Not_confident == 1 ~ 0,
      q19_2lvl_Confident == 1 ~ 1,
      TRUE ~ NA
    ),
    q20_dum = dplyr::case_when(
      q20_2lvl_Not_confident == 1 ~ 0,
      q20_2lvl_Confident == 1 ~ 1,
      TRUE ~ NA
    ),
    q22_dum = dplyr::case_when(
      q22_2lvl_Not_confident == 1 ~ 0,
      q22_2lvl_Confident == 1 ~ 1,
      TRUE ~ NA
    ),
    q23_dum = dplyr::case_when(
      q23_2lvl_Not_confident == 1 ~ 0,
      q23_2lvl_Confident == 1 ~ 1,
      TRUE ~ NA
    ),
    q24_dum = dplyr::case_when(
      q24_2lvl_Not_confident == 1 ~ 0,
      q24_2lvl_Confident == 1 ~ 1,
      TRUE ~ NA
    ),
    q26_dum = dplyr::case_when(
      q26_2lvl_Not_confident == 1 ~ 0,
      q26_2lvl_Confident == 1 ~ 1,
      TRUE ~ NA
    ),
    q30_dum = dplyr::case_when(
      q30_2lvl_Not_confident == 1 ~ 0,
      q30_2lvl_Confident == 1 ~ 1,
      TRUE ~ NA
    ),
    q31_dum = dplyr::case_when(
      q31_2lvl_Not_confident == 1 ~ 0,
      q31_2lvl_Confident == 1 ~ 1,
      TRUE ~ NA
    ),
    q33_dum = dplyr::case_when(
      q33_2lvl_Not_confident == 1 ~ 0,
      q33_2lvl_Confident == 1 ~ 1,
      TRUE ~ NA
    ),
    q34_dum = dplyr::case_when(
      q34_2lvl_Not_confident == 1 ~ 0,
      q34_2lvl_Confident == 1 ~ 1,
      TRUE ~ NA
    ),
    q35_dum = dplyr::case_when(
      q35_2lvl_Not_confident == 1 ~ 0,
      q35_2lvl_Confident == 1 ~ 1,
      TRUE ~ NA
    ),
    q37_dum = dplyr::case_when(
      q37_2lvl_Not_confident == 1 ~ 0,
      q37_2lvl_Confident == 1 ~ 1,
      TRUE ~ NA
    ),
    .keep = "unused"
  )



```

```{r}
#| label: dumdf2

dum_q2132 <- data |>
  select(rowID, q21, q32) |> 
  mutate(across(c(q21, q32), ~forcats::fct_collapse(
    .,
    not_committed = c("Not at all committed", "Not too committed"),
    committed = c("Somewhat committed", "Very committed")))) 

dum_q2132 <- dum_q2132 |> 
  select(rowID, q21, q32) |> 
  pewmethods::dummify_factors(sep = "_") |> 
  mutate(
    q21_dum = dplyr::case_when(
      q21_not_committed == 1 ~ 0,
      q21_committed == 1 ~ 1,
      TRUE ~ NA),
    q32_dum = dplyr::case_when(
      q32_not_committed == 1 ~ 0,
      q32_committed == 1 ~ 1,
      TRUE ~ NA),
    .keep = "unused"
  )



```


```{r}
# dummy q25 q36 

dum_q2536 <- data |>
  select(rowID, q25, q36) |>
  # whoops. Need to change "somewhat unconcerned" to "Not too concerned"
  # recall: fct_recode(x, old_level = new_level)
  mutate(q36 =forcats::fct_recode(
    q36, 
    "Not at all concerned" = "Not at all concerned",
    "Not too concerned" = "Somewhat unconcerned",
    "Somewhat concerned" = "Somewhat concerned",
    "Very concerned" = "Very concerned")
    ) |>
  mutate(across(
    c(q25, q36),
    ~ forcats::fct_collapse(
      .,
      not_concerned = c("Not at all concerned", "Not too concerned"),
      concerned = c("Somewhat concerned", "Very concerned")
    )
  )) 

dum_q2536 <- dum_q2536 |> 
  select(rowID, q25, q36) |> 
  pewmethods::dummify_factors(sep = "_") |> 
  mutate(
    q25_dum = dplyr::case_when(
      q25_not_concerned == 1 ~ 0,
      q25_concerned == 1 ~ 1,
      TRUE ~ NA),
    q36_dum = dplyr::case_when(
      q36_not_concerned == 1 ~ 0,
      q36_concerned == 1 ~ 1,
      TRUE ~ NA),
    .keep = "unused"
  )


```


```{r}
# dummy q38 
dum_q38 <- data |>
  select(rowID, q38) |>
  mutate(q38 =
           forcats::fct_collapse(
             q38,
             unsafe = c("Not safe at all", "Not too safe"),
             safe = c("Somewhat safe", "Very safe")))


dum_q38 <- dum_q38 |> 
  select(rowID, q38) |> 
  pewmethods::dummify_factors(sep = "_") |> 
  mutate(
    q38_dum = dplyr::case_when(
      q38_unsafe == 1 ~ 0,
      q38_safe == 1 ~ 1,
      TRUE ~ NA),
    .keep = "unused"
  )

```


```{r}


# dummy q27 q39 
dum_q2739 <- data |>
  select(rowID, q27, q39) |>
  mutate(across(
    c(q27, q39),
    ~ forcats::fct_collapse(
      .,
      disapprove = c("Strongly disapprove", "Somewhat disapprove" ),
      approve = c("Somewhat approve", "Strongly approve")
    )
  )) 


dum_q2739 <- dum_q2739 |> 
  select(rowID, q27, q39) |> 
  pewmethods::dummify_factors(sep = "_") |> 
  mutate(
    q27_dum = dplyr::case_when(
      q27_disapprove == 1 ~ 0,
      q27_approve == 1 ~ 1,
      TRUE ~ NA),
    q39_dum = dplyr::case_when(
      q39_disapprove == 1 ~ 0,
      q39_approve == 1 ~ 1,
      TRUE ~ NA),
    .keep = "unused"
  )






```


```{r}

# dummy q29 

dum_q29 <- data |>
  select(rowID, q29) |>
  mutate(q29 = forcats::fct_collapse(q29,
      oppose = c("Definitely should not adopt", "Probably should not adopt"),
      support = c("Probably should adopt", "Definitely should adopt")
    )) 

dum_q29 <- dum_q29 |> 
  select(rowID, q29) |> 
  pewmethods::dummify_factors(sep = "_") |> 
  mutate(
    q29_dum = dplyr::case_when(
      q29_oppose == 1 ~ 0,
      q29_support == 1 ~ 1,
      TRUE ~ NA),
    .keep = "unused"
  )


```


```{r}

# dummy q28 q40 


# collapse factor vars and add new collapsed factors to data frame
dum_2840 <- data |>
  select(rowID, contains("28_"), contains("40_")) |> 
  mutate(across(contains("_"), ~forcats::fct_collapse(
    .,
    Not_likely = c("Not likely at all", "Not too likely"),
    Likely = c("Somewhat likely", "Very likely")),
    .names = "{.col}_2lvl"))

dum_2840 <- dum_2840 |> 
  select(rowID, contains("_2lvl")) |> 
  pewmethods::dummify_factors(sep = "_") |>  
  mutate(
    q28_1_dum = dplyr::case_when(
    q28_1_2lvl_Not_likely == 1 ~ 0,
    q28_1_2lvl_Likely == 1 ~ 1,
    TRUE ~ NA),
    q28_2_dum = dplyr::case_when(
    q28_2_2lvl_Not_likely == 1 ~ 0,
    q28_2_2lvl_Likely == 1 ~ 1,
    TRUE ~ NA),
    q28_3_dum = dplyr::case_when(
    q28_3_2lvl_Not_likely == 1 ~ 0,
    q28_3_2lvl_Likely == 1 ~ 1,
    TRUE ~ NA),
    q28_4_dum = dplyr::case_when(
    q28_4_2lvl_Not_likely == 1 ~ 0,
    q28_4_2lvl_Likely == 1 ~ 1,
    TRUE ~ NA),
    q28_5_dum = dplyr::case_when(
    q28_5_2lvl_Not_likely == 1 ~ 0,
    q28_5_2lvl_Likely == 1 ~ 1,
    TRUE ~ NA),
    q40_1_dum = dplyr::case_when(
    q40_1_2lvl_Not_likely == 1 ~ 0,
    q40_1_2lvl_Likely == 1 ~ 1,
    TRUE ~ NA),
    q40_2_dum = dplyr::case_when(
    q40_2_2lvl_Not_likely == 1 ~ 0,
    q40_2_2lvl_Likely == 1 ~ 1,
    TRUE ~ NA),
    q40_3_dum = dplyr::case_when(
    q40_3_2lvl_Not_likely == 1 ~ 0,
    q40_3_2lvl_Likely == 1 ~ 1,
    TRUE ~ NA),
    q40_4_dum = dplyr::case_when(
    q40_4_2lvl_Not_likely == 1 ~ 0,
    q40_4_2lvl_Likely == 1 ~ 1,
    TRUE ~ NA),
    q40_5_dum = dplyr::case_when(
    q40_5_2lvl_Not_likely == 1 ~ 0,
    q40_5_2lvl_Likely == 1 ~ 1,
    TRUE ~ NA),
    .keep = "unused"
    )




```


```{r}


# dummy q41 q43 q44 q46 

# collapse factor vars and add new collapsed factors to data frame
# I can't really "dummify" these factors into simply binary variables with
# values 1, 0. There were five response options with a neutral middle.
dum_q41434446 <- data |>
  select(rowID, 
         contains("41_"),
         contains("43_"), 
         contains("44_"),
         contains("46_")
         ) |>  
  mutate(across(contains("_"), ~forcats::fct_collapse(
    .,
    decrease = c("Decrease confidence a lot",
                      "Decrease confidence somewhat"),
    no_impact = "No impact on confidence",
    increase = c("Increase confidence somewhat",
                      "Increase confidence a lot"))))


dum_q41434446 <- dum_q41434446 |> 
  select(rowID, contains("_")) |> 
  pewmethods::dummify_factors(sep = "_") |>
  mutate(
    q41_1_clps = dplyr::case_when(
    q41_1_decrease == 1 ~ -1,
    q41_1_no_impact == 1 ~ 0,
    q41_1_increase == 1 ~ 1,
    TRUE ~ NA),
    q41_2_clps = dplyr::case_when(
    q41_2_decrease == 1 ~ -1,
    q41_2_no_impact == 1 ~ 0,
    q41_2_increase == 1 ~ 1,
    TRUE ~ NA),
    q41_3_clps = dplyr::case_when(
    q41_3_decrease == 1 ~ -1,
    q41_3_no_impact == 1 ~ 0,
    q41_3_increase == 1 ~ 1,
    TRUE ~ NA),
    q41_4_clps = dplyr::case_when(
    q41_4_decrease == 1 ~ -1,
    q41_4_no_impact == 1 ~ 0,
    q41_4_increase == 1 ~ 1,
    TRUE ~ NA),
    q41_5_clps = dplyr::case_when(
    q41_5_decrease == 1 ~ -1,
    q41_5_no_impact == 1 ~ 0,
    q41_5_increase == 1 ~ 1,
    TRUE ~ NA),
    q41_6_clps = dplyr::case_when(
    q41_6_decrease == 1 ~ -1,
    q41_6_no_impact == 1 ~ 0,
    q41_6_increase == 1 ~ 1,
    TRUE ~ NA),
    q43_1_clps = dplyr::case_when(
    q43_1_decrease == 1 ~ -1,
    q43_1_no_impact == 1 ~ 0,
    q43_1_increase == 1 ~ 1,
    TRUE ~ NA),
    q43_2_clps = dplyr::case_when(
    q43_2_decrease == 1 ~ -1,
    q43_2_no_impact == 1 ~ 0,
    q43_2_increase == 1 ~ 1,
    TRUE ~ NA),
    q43_3_clps = dplyr::case_when(
    q43_3_decrease == 1 ~ -1,
    q43_3_no_impact == 1 ~ 0,
    q43_3_increase == 1 ~ 1,
    TRUE ~ NA),
    q43_4_clps = dplyr::case_when(
    q43_4_decrease == 1 ~ -1,
    q43_4_no_impact == 1 ~ 0,
    q43_4_increase == 1 ~ 1,
    TRUE ~ NA),
    q43_5_clps = dplyr::case_when(
    q43_5_decrease == 1 ~ -1,
    q43_5_no_impact == 1 ~ 0,
    q43_5_increase == 1 ~ 1,
    TRUE ~ NA),
    q43_6_clps = dplyr::case_when(
    q43_6_decrease == 1 ~ -1,
    q43_6_no_impact == 1 ~ 0,
    q43_6_increase == 1 ~ 1,
    TRUE ~ NA),
    q44_1_clps = dplyr::case_when(
    q44_1_decrease == 1 ~ -1,
    q44_1_no_impact == 1 ~ 0,
    q44_1_increase == 1 ~ 1,
    TRUE ~ NA),
    q44_2_clps = dplyr::case_when(
    q44_2_decrease == 1 ~ -1,
    q44_2_no_impact == 1 ~ 0,
    q44_2_increase == 1 ~ 1,
    TRUE ~ NA),
    q44_3_clps = dplyr::case_when(
    q44_3_decrease == 1 ~ -1,
    q44_3_no_impact == 1 ~ 0,
    q44_3_increase == 1 ~ 1,
    TRUE ~ NA),
    q44_4_clps = dplyr::case_when(
    q44_4_decrease == 1 ~ -1,
    q44_4_no_impact == 1 ~ 0,
    q44_4_increase == 1 ~ 1,
    TRUE ~ NA),
    q44_5_clps = dplyr::case_when(
    q44_5_decrease == 1 ~ -1,
    q44_5_no_impact == 1 ~ 0,
    q44_5_increase == 1 ~ 1,
    TRUE ~ NA),
    q44_6_clps = dplyr::case_when(
    q44_6_decrease == 1 ~ -1,
    q44_6_no_impact == 1 ~ 0,
    q44_6_increase == 1 ~ 1,
    TRUE ~ NA),
    q46_1_clps = dplyr::case_when(
    q46_1_decrease == 1 ~ -1,
    q46_1_no_impact == 1 ~ 0,
    q46_1_increase == 1 ~ 1,
    TRUE ~ NA),
    q46_2_clps = dplyr::case_when(
    q46_2_decrease == 1 ~ -1,
    q46_2_no_impact == 1 ~ 0,
    q46_2_increase == 1 ~ 1,
    TRUE ~ NA),
    q46_3_clps = dplyr::case_when(
    q46_3_decrease == 1 ~ -1,
    q46_3_no_impact == 1 ~ 0,
    q46_3_increase == 1 ~ 1,
    TRUE ~ NA),
    q46_4_clps = dplyr::case_when(
    q46_4_decrease == 1 ~ -1,
    q46_4_no_impact == 1 ~ 0,
    q46_4_increase == 1 ~ 1,
    TRUE ~ NA),
    q46_5_clps = dplyr::case_when(
    q46_5_decrease == 1 ~ -1,
    q46_5_no_impact == 1 ~ 0,
    q46_5_increase == 1 ~ 1,
    TRUE ~ NA),
    q46_6_clps = dplyr::case_when(
    q46_6_decrease == 1 ~ -1,
    q46_6_no_impact == 1 ~ 0,
    q46_6_increase == 1 ~ 1,
    TRUE ~ NA),
    .keep = "unused"
    )

```


```{r}

df <- datawizard::data_merge(data, dumdf, join = "left", by = "rowID")

df <- datawizard::data_merge(df, dum_q2132, join = "left", by = "rowID") |> 
  dplyr::relocate(q21_dum, .after = q20_dum) |> 
  dplyr::relocate(q32_dum, .after = q31_dum)

df <- datawizard::data_merge(df, dum_q2536, join = "left", by = "rowID")

df <- df |> dplyr::relocate(q25_dum, .before = q26_dum)

df <- datawizard::data_merge(df, dum_q38, join = "left", by = "rowID") |> 
  dplyr::relocate(q38_dum, .after = q37_dum)

df <- datawizard::data_merge(df, dum_q2739, join = "left", by = "rowID") |> 
  dplyr::relocate(q27_dum, .after = q26_dum) |> 
  dplyr::relocate(q39_dum, .after = q38_dum)

df <- datawizard::data_merge(df, dum_q29, join = "left", by = "rowID") |> 
  dplyr::relocate(q29_dum, .after = q27_dum)

df <- datawizard::data_merge(df, dum_2840, join = "left", by = "rowID") |> 
  dplyr::relocate(q28_1_dum:q28_5_dum, .after = q27_dum) |> 
  dplyr::relocate(q40_1_dum:q40_5_dum, .after = q39_dum)

df <- datawizard::data_merge(df, dum_q41434446, join = "left", by = "rowID") |> 
  dplyr::relocate(q41_1_clps:q41_6_clps, .after = q40_5_dum) |> 
  dplyr::relocate(q43_1_clps:q43_6_clps, .after = q41_6_clps) |> 
  dplyr::relocate(q44_1_clps:q44_6_clps, .after = q43_6_clps) |> 
  dplyr::relocate(q46_1_clps:q46_6_clps, .after = q44_6_clps)

```
